In [1]:
!pip install corus
from corus import load_lenta
import pandas as pd
import numpy as np
import spacy

from sklearn.metrics import f1_score, classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import LabelEncoder



from tqdm.notebook import tqdm

#Активируем tqdm для pandas
tqdm.pandas()

##Выгрузка данных

In [9]:
!wget https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz

--2025-03-04 10:50:53--  https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250304%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250304T105053Z&X-Amz-Expires=300&X-Amz-Signature=c94f3617a5518ca1bdbe074c8351777070a96138cbc2e34d44142da41bb43b51&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream [following]
--2025-03-04 10:50:53--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250304%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250304T105053Z&X-Amz-Expires=300&X-Amz-Signature=c94f3617a5518ca1bdbe074c8351777070a96138cbc2e34d44142da41bb43b51&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 527373240 (503M) [application/octet-stream]
Saving to: ‘lenta-ru-news.csv.gz’

lenta-ru-news.csv.g 100%[===================>] 502.94M  99.9MB/s    in 5.0s

2025-03-04 10:50:58 (101 MB/s) - ‘lenta-ru-news.csv.gz’ saved [527373240/527373240]

In [10]:
path = 'lenta-ru-news.csv.gz'
records = load_lenta(path)
next(records)

LentaRecord(
    url='https://lenta.ru/news/2018/12/14/cancer/',
    title='Названы регионы России с\xa0самой высокой смертностью от\xa0рака',
    text='Вице-премьер по социальным вопросам Татьяна Голикова рассказала, в каких регионах России зафиксирована наиболее высокая смертность от рака, сообщает РИА Новости. По словам Голиковой, чаще всего онкологические заболевания становились причиной смерти в Псковской, Тверской, Тульской и Орловской областях, а также в Севастополе. Вице-премьер напомнила, что главные факторы смертности в России — рак и болезни системы кровообращения. В начале года стало известно, что смертность от онкологических заболеваний среди россиян снизилась впервые за три года. По данным Росстата, в 2017 году от рака умерли 289 тысяч человек. Это на 3,5 процента меньше, чем годом ранее.',
    topic='Россия',
    tags='Общество',
    date=None
)

In [11]:
# отберем нужные атрибуты новостей и запишем их в датафрейм
topics = []
texts = []
titles = []
for record in records:

    topic = record.topic
    topics.append(topic)

    title = record.title
    titles.append(title)

    text = record.text
    texts.append(text)

lenta_df = pd.DataFrame({'text' : texts,
                         'title' : titles,
                         'topic' : topics})

print("DF shape:",lenta_df.shape[0])
lenta_df.head(3)

DF shape: 739350

,text,title,topic
0,Австрийские правоохранительные органы не предс...,Австрия не представила доказательств вины росс...,Спорт
1,Сотрудники социальной сети Instagram проанализ...,Обнаружено самое счастливое место на планете,Путешествия
2,С начала расследования российского вмешательст...,В США раскрыли сумму расходов на расследование...,Мир

In [12]:
# проверим, что все корректно записалось в датафрейм, нет пустых ячеек
lenta_df.isna().sum()

text     0
title    0
topic    0
dtype: int64

In [13]:
lenta_df.dtypes

text     object
title    object
topic    object
dtype: object

In [14]:
# распределение новостей по топикам
lenta_df['topic'].value_counts(normalize=True)

topic
Россия               0.217107
Мир                  0.184865
Экономика            0.107578
Спорт                0.087132
Культура             0.072771
Бывший СССР          0.072228
Наука и техника      0.071869
Интернет и СМИ       0.060425
Из жизни             0.037345
Дом                  0.029396
Силовые структуры    0.026504
Ценности             0.010504
Бизнес               0.010007
Путешествия          0.008667
69-я параллель       0.001715
Крым                 0.000901
Культпросвет         0.000460
                     0.000275
Легпром              0.000154
Библиотека           0.000088
Оружие               0.000004
ЧМ-2014              0.000003
МедНовости           0.000001
Сочи                 0.000001
Name: proportion, dtype: float64

In [15]:
#Есть новости, где тема - пустая строка
lenta_df.query('topic == ""')

,text,title,topic
3529,В учебном центре врачебной практики Praxi Medi...,Японский профессор рассказал о свойствах молек...,
8735,Организаторы выставки «ИгроМир» и фестиваля Co...,Подведены итоги «ИгроМира» и Comic Con Russia,
9955,Российская студия разработчиков Enplex Games р...,Московские разработчики показали Population Zero,
10307,Современный рынок товаров и услуг настолько ра...,Подведены итоги IX ежегодной премии «Права пот...,
16332,Оргкомитет Восточного экономического форума на...,Опубликована деловая программа Восточного экон...,
...,...,...,...
624784,Министр финансов Люксембурга Жан-Клод Джанкер ...,"Люксембург недоволен экономическим пактом, раз...",
625196,Председатель комитета Госдумы по аграрным вопр...,Исправление ошибок монетизации обошлось бюджет...,
625953,23 февраля в Москве прошли праздничные митинги...,Московские левые отметили 23 февраля шествием ...,
626318,Во Франции опубликован словарь из 3 тысяч бюро...,Французы перестали понимать своих бюрократов,
626362,Президент РФ Владимир Путин подписал указы о п...,Путин повысил довольствие военнослужащим и пен...,

In [16]:
#Исключим такие новости с пустой темой
lenta_df = lenta_df.query('topic != ""').reset_index(drop=True)
print('DF shape:', lenta_df.shape[0])
lenta_df.head(3)

DF shape: 739147

,text,title,topic
0,Австрийские правоохранительные органы не предс...,Австрия не представила доказательств вины росс...,Спорт
1,Сотрудники социальной сети Instagram проанализ...,Обнаружено самое счастливое место на планете,Путешествия
2,С начала расследования российского вмешательст...,В США раскрыли сумму расходов на расследование...,Мир

In [17]:
lenta_df['topic'].value_counts(normalize=True)

topic
Россия               0.217167
Мир                  0.184916
Экономика            0.107608
Спорт                0.087156
Культура             0.072791
Бывший СССР          0.072248
Наука и техника      0.071888
Интернет и СМИ       0.060441
Из жизни             0.037355
Дом                  0.029404
Силовые структуры    0.026512
Ценности             0.010507
Бизнес               0.010010
Путешествия          0.008669
69-я параллель       0.001715
Крым                 0.000901
Культпросвет         0.000460
Легпром              0.000154
Библиотека           0.000088
Оружие               0.000004
ЧМ-2014              0.000003
МедНовости           0.000001
Сочи                 0.000001
Name: proportion, dtype: float64

In [18]:
# уменьшим датафрейм до 100 000 новостей с сохранением пропорции по частоте тем

sample_size = 100000

proportions = lenta_df['topic'].value_counts(normalize=True)

# Количество строк по каждой теме
sample_counts = (proportions * sample_size).round().astype(int)

# Создаем стратифицированную выборку из новостей
news_df = pd.concat([
                    lenta_df[lenta_df['topic'] == topic].sample(n=count, random_state=42)
                    for topic, count in sample_counts.items()
                    ])\
            .copy()

# Если сумма news_df не равна 100 000 из-за округления, можно добавить или убрать несколько строк
if len(news_df) > sample_size:
    news_df = news_df.sample(n=sample_size, random_state=42)
elif len(news_df) < sample_size:
    additional_samples = news_df[~lenta_df.index.isin(news_df.index)].sample(n=sample_size - len(news_df), random_state=42)
    news_df = pd.concat([news_df, additional_samples])

news_df = news_df.reset_index(drop=True)
news_df

,text,title,topic
0,"Движение ""Хизбалла"" объявило о выводе своих во...","""Хизбалла"" выводит свои подразделения из Бейрута",Мир
1,Дэвид Кроненберг намерен снять продолжение сво...,"Кроненберг снимет сиквел ""Порока на экспорт""",Культура
2,По крайней мере 27 человек погибли и 21 получи...,Смертник взорвал афганских военных в Кабуле,Россия
3,Чемпион Олимпиады-2004 в Афинах кубинец Одлань...,Чемпион Олимпиады-2004 бросил вызов Владимиру ...,Спорт
4,Российские фондовые индексы в начале торгов 8 ...,РТС и ММВБ начали неделю с резкого роста,Экономика
...,...,...,...
99995,Первый заместитель председателя правительства ...,Шувалов расскажет на НТВ о пьяных водителях,Интернет и СМИ
99996,Задержанный пограничниками КНДР российский теп...,Захваченное российское судно следует в северок...,Россия
99997,"Российский боксер Султан Ибрагимов, чемпион ми...",Султан Ибрагимов прилетел в Москву на бой с Хо...,Спорт
99998,"Источником быстрых радиоимпульсов, которые ряд...",Ученые локализовали источник «инопланетного» с...,Наука и техника
99999,Дело Михаила Ходорковского будет передано в су...,Дело Ходорковского в ближайшее время передадут...,Россия

In [19]:
#Проверим пропорции исходного датафрейма и полученной выборки
proportions.reset_index().merge(news_df['topic'].value_counts(normalize=True),
                                how='left',
                                on='topic',
                                suffixes=('_all', '_sample'),
                                validate='m:1'
                                )

                topic  proportion_all  proportion_sample
0              Россия        0.217167            0.21716
1                 Мир        0.184916            0.18492
2           Экономика        0.107608            0.10761
3               Спорт        0.087156            0.08716
4            Культура        0.072791            0.07279
5         Бывший СССР        0.072248            0.07225
6     Наука и техника        0.071888            0.07189
7      Интернет и СМИ        0.060441            0.06044
8            Из жизни        0.037355            0.03736
9                 Дом        0.029404            0.02940
10  Силовые структуры        0.026512            0.02651
11           Ценности        0.010507            0.01051
12             Бизнес        0.010010            0.01001
13        Путешествия        0.008669            0.00867
14     69-я параллель        0.001715            0.00172
15               Крым        0.000901            0.00090
16      Культпросвет         0.000460            0.00046
17            Легпром        0.000154            0.00015
18         Библиотека        0.000088            0.00009
19             Оружие        0.000004                NaN
20            ЧМ-2014        0.000003                NaN
21         МедНовости        0.000001                NaN
22               Сочи        0.000001                NaN

Пропорции в целом сохранены, но несколько тем выпало из-за очень редкой встречаемости

In [20]:
# удалим исходный датасет и ненужные списки
del lenta_df, topics

##Предобработка

In [21]:
# установим модель для обработки русских текстов в spacy
!python -m spacy download ru_core_news_sm

Collecting ru-core-news-sm==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ru_core_news_sm-3.7.0/ru_core_news_sm-3.7.0-py3-none-any.whl (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 80.2 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from ru-core-news-sm==3.7.0) (3.7.5)
Collecting pymorphy3>=1.0.0 (from ru-core-news-sm==3.7.0)
  Downloading pymorphy3-2.0.3-py3-none-any.whl.metadata (1.9 kB)
Collecting dawg2-python>=0.8.0 (from pymorphy3>=1.0.0->ru-core-news-sm==3.7.0)
  Downloading dawg2_python-0.9.0-py3-none-any.whl.metadata (7.5 kB)
Collecting pymorphy3-dicts-ru (from pymorphy3>=1.0.0->ru-core-news-sm==3.7.0)
  Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.10.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.1.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2025.1.31)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->ru-core-news-sm==3.7.0) (0.1.2)
Downloading pymorphy3-2.0.3-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.8/53.8 kB 3.3 MB/s eta 0:00:00
Downloading dawg2_python-0.9.0-py3-none-any.whl (9.3 kB)
Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 92.1 MB/s eta 0:00:00
Installing collected packages: pymorphy3-dicts-ru, dawg2-python, pymorphy3, ru-core-news-sm
Successfully installed dawg2-python-0.9.0 pymorphy3-2.0.3 pymorphy3-dicts-ru-2.4.417150.4580142 ru-core-news-sm-3.7.0
✔ Download and installation successful
You can now load the package via spacy.load('ru_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [23]:
# загрузка пайплайна обработки текста spacy, отключим блоки parser и ner в модели spacy для ускорения
nlp = spacy.load("ru_core_news_sm", disable=['parser', 'ner'])
stopwords = nlp.Defaults.stop_words
print(f'Количество стоп-слов в русском языке: {len(stopwords)}')

Количество стоп-слов в русском языке: 768

In [30]:
# Используем nlp.pipe и батчи для обработки

# Преобразуем тексты в список для обработки батчами
texts = news_df['text'].to_list()

# Обработка текстов батчами
cleaned_texts = []
for doc in tqdm(nlp.pipe(texts, batch_size=50, n_process=-1),  total=len(texts)):  # n_process=-1 используем все ядра CPU
    cleaned_text = ' '.join(
        token.lemma_.lower() for token in doc if
        not token.is_stop  # не стоп слово
        and not token.is_punct  # не пунктуация
        and not token.is_digit  # не цифра
        and not token.like_email  # не имейл
        and not token.like_num  # не похоже на число
        and not token.is_space  # не пробел
        and not token.is_bracket  # не скобки
    )
    cleaned_texts.append(cleaned_text)

# Добавляем результат в DataFrame
news_df['cleaned_text'] = cleaned_texts

  0%|          | 0/100000 [00:00<?, ?it/s]

In [35]:
# вроде бы досаточно неплохо получилось предобработать текст
news_df['cleaned_text'][0]

'движение хизбалла объявить вывод вооружить подразделение бейрут сообщать суббота afp ссылка ливанский телевидение боевик попросить военный взять город контроль начать покидать захваченные район заявление хизбаллы сказать акция гражданский неповиновение продолжиться применение огнестрельный оружие ливанский военный призвать участник конфликт сложить оружие разойтись дом сделать обращение премьер министр страна фуад синиоры нация армия решение власть отказаться силовой метод очистить улица бейрут обратиться конфликтовать предложение мирный путь решение кризис конфликт оппозиция поддерживать правительство ливан группировка начаться вторник повод боестолкновений послужить заявление власть контролировать хизбаллой телекоммуникационный компания осуществлять незаконный деятельность правительство сместить пост глава служба безопасность аэропорт имя рафик харири связать шиит ход противостояние убить человек десяток получить ранение движение хизбалла конфликт удаться взять контроль аэропорт значительный часть бейрут'

In [36]:
# Преобразуем тексты в список для обработки батчами
titles = news_df['title'].to_list()

# Обработка заголовков батчами
cleaned_titles = []
for doc in tqdm(nlp.pipe(titles, batch_size=100, n_process=-1),  total=len(titles)):  # n_process=-1 используем все ядра CPU
    cleaned_title = ' '.join(
        token.lemma_.lower() for token in doc if
        not token.is_stop  # не стоп слово
        and not token.is_punct  # не пунктуация
        and not token.is_digit  # не цифра
        and not token.like_email  # не имейл
        and not token.like_num  # не похоже на число
        and not token.is_space  # не пробел
        and not token.is_bracket  # не скобки
    )
    cleaned_titles.append(cleaned_title)

# Добавляем результат в DataFrame
news_df['cleaned_title'] = cleaned_titles

  0%|          | 0/100000 [00:00<?, ?it/s]

In [37]:
# вроде бы тоже относительно неплохо
news_df['cleaned_title'][:5]

0               хизбалла выводить подразделение бейрут
1               кроненберг снять сиквел порока экспорт
2            смертник взорвать афганский военный кабул
3    чемпион олимпиады-2004 бросить вызов владимир ...
4                   ртс ммвб начать неделя резкий рост
Name: cleaned_title, dtype: object

In [40]:
# удалим колонки text и title
news_df = news_df.drop(columns=['text', 'title'])
news_df.head(3)

,topic,cleaned_text,cleaned_title
0,Мир,движение хизбалла объявить вывод вооружить под...,хизбалла выводить подразделение бейрут
1,Культура,дэвид кроненберг намеренный снять продолжение ...,кроненберг снять сиквел порока экспорт
2,Россия,крайний мера человек погибнуть получить ранени...,смертник взорвать афганский военный кабул

## Бейзлайн с помощью dummy classifier

In [3]:
# Шаг 1: Разделяем на обучающую (60%) и временную (40%) выборки
train_df, temp_df = train_test_split(news_df, test_size=0.4, stratify=news_df['topic'], random_state=42)

# Шаг 2: Разделяем временную выборку на валидационную (20%) и тестовую (20%)
val_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df['topic'], random_state=42)

# Проверяем размеры выборок
print(f"Обучающая выборка: {len(train_df)}")
print(f"Валидационная выборка: {len(val_df)}")
print(f"Тестовая выборка: {len(test_df)}")

Обучающая выборка: 60000
Валидационная выборка: 20000
Тестовая выборка: 20000

Выборки разделились правильно

In [5]:
# Закодируем целевую переменную с помощью label encoder (для dummy без разницы как кодировать)
encoder = LabelEncoder()
y_train = encoder.fit_transform(train_df['topic'])
y_val = encoder.transform(val_df['topic'])
y_test = encoder.transform(test_df['topic'])

# Выведем результат
print("y_train:\n", y_train)
print("y_val:\n", y_val)
print("y_test:\n", y_test)

y_train:
 [ 5  3 14 ... 11  9 11]
y_val:
 [12  6 18 ... 11  6 16]
y_test:
 [ 6  6 14 ... 14  5 11]

In [6]:
# Создание и обучение DummyClassifier по самому частотному классу
dummy_clf = DummyClassifier(strategy="most_frequent")

# Обучаем модель (передаем пустой массив, модель все равно не смотрит на данные X)
dummy_clf.fit(np.zeros((len(y_train), 1)), y_train)

# Предсказание на валидационной выборке (передаем пустой массив вместо X)
y_pred_val = dummy_clf.predict(np.zeros((len(y_val), 1)))

# Оценка качества на валидационной выборке
print("Dummy Classifier (валидационная выборка):")
print(classification_report(y_val, y_pred_val, target_names=encoder.classes_, zero_division=0))

# Предсказание на тестовой выборке (передаем пустой массив)
y_pred_test = dummy_clf.predict(np.zeros((len(y_test), 1)))

# Оценка качества на тестовой выборке
print("Dummy Classifier (тестовая выборка):")
print(classification_report(y_test, y_pred_test, target_names=encoder.classes_, zero_division=0))

Dummy Classifier (валидационная выборка):
                   precision    recall  f1-score   support

   69-я параллель       0.00      0.00      0.00        34
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.00      0.00      0.00       200
      Бывший СССР       0.00      0.00      0.00      1445
              Дом       0.00      0.00      0.00       588
         Из жизни       0.00      0.00      0.00       747
   Интернет и СМИ       0.00      0.00      0.00      1209
             Крым       0.00      0.00      0.00        18
    Культпросвет        0.00      0.00      0.00         9
         Культура       0.00      0.00      0.00      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.00      0.00      0.00      3699
  Наука и техника       0.00      0.00      0.00      1438
      Путешествия       0.00      0.00      0.00       173
           Россия       0.22      1.00      0.36      4343
Силовые структуры       0.00      0.00      0.00       530
            Спорт       0.00      0.00      0.00      1743
         Ценности       0.00      0.00      0.00       210
        Экономика       0.00      0.00      0.00      2153

         accuracy                           0.22     20000
        macro avg       0.01      0.05      0.02     20000
     weighted avg       0.05      0.22      0.08     20000

Dummy Classifier (тестовая выборка):
                   precision    recall  f1-score   support

   69-я параллель       0.00      0.00      0.00        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.00      0.00      0.00       200
      Бывший СССР       0.00      0.00      0.00      1445
              Дом       0.00      0.00      0.00       588
         Из жизни       0.00      0.00      0.00       747
   Интернет и СМИ       0.00      0.00      0.00      1209
             Крым       0.00      0.00      0.00        18
    Культпросвет        0.00      0.00      0.00         9
         Культура       0.00      0.00      0.00      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.00      0.00      0.00      3698
  Наука и техника       0.00      0.00      0.00      1438
      Путешествия       0.00      0.00      0.00       174
           Россия       0.22      1.00      0.36      4343
Силовые структуры       0.00      0.00      0.00       530
            Спорт       0.00      0.00      0.00      1743
         Ценности       0.00      0.00      0.00       210
        Экономика       0.00      0.00      0.00      2152

         accuracy                           0.22     20000
        macro avg       0.01      0.05      0.02     20000
     weighted avg       0.05      0.22      0.08     20000

Таким образом, мы получили базовый уровень качества, когда мы просто присваиваем самую частотную тему (Россия) любой новости.

Средненвзвешенный recall - 22% и precision - 5%, f1 - 0.08

Будем пробовать улучшать :)

##Разные подходы и способы к векторизации BagOfWords и TF-IDF

Попробуем конкатенировать текст и заголовок и построить на объединенном тексте векторы

In [5]:
train_df['combined'] = train_df['cleaned_text'] + ' ' +  train_df['cleaned_title']
test_df['combined'] = test_df['cleaned_text'] + ' ' +  test_df['cleaned_title']
val_df['combined'] = val_df['cleaned_text'] + ' ' +  val_df['cleaned_title']

train_df.head(3)

,topic,cleaned_text,cleaned_title,combined
59911,Из жизни,рэпер филадельфия мик милл meek mill обязанный...,суд отправить рэпер филадельфия курс этикет,рэпер филадельфия мик милл meek mill обязанный...
25146,Бывший СССР,комитет верховный рада украина вопрос наука об...,рада предложить отказаться имя русский царь на...,комитет верховный рада украина вопрос наука об...
96947,Россия,бывший глава управление федеральный казначейст...,бывший главный казначей оренбуржья посадить на...,бывший глава управление федеральный казначейст...

In [7]:
# max_df фильтрует corpus-specifiс по частнотности, по сути кастомные stop words
count_vectorizer = CountVectorizer(max_df=0.7, min_df=0.001)

X_train_vectorized_bow = count_vectorizer.fit_transform(train_df['combined'])  # Обучение векторизатора и преобразование train
X_test_vectorized_bow = count_vectorizer.transform(test_df['combined'])       # Преобразование test
X_val_vectorized_bow = count_vectorizer.transform(val_df['combined']) # преобразование val

In [8]:
print('Количество уникальных токенов в нашем корпусе:',len(count_vectorizer.get_feature_names_out()))

Количество уникальных токенов в нашем корпусе: 9149

In [9]:
# количество колонок должно совпадать с уникальными токенами корпуса, а количество строк с количеством строк в трейн дс

matrix = pd.DataFrame(X_train_vectorized_bow.toarray(), columns=count_vectorizer.get_feature_names_out())

assert matrix.shape[0] == train_df.shape[0] and len(matrix.columns) == len(count_vectorizer.get_feature_names_out())

matrix.head(3)

,00,01,02,03,04,05,06,07,08,09,...,ярославль,ярославский,ясир,ясный,яхта,яценюк,ячейка,яшин,ящик,ёмкость
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
del matrix

Как доработка, можно попробовать затем убрать вот такие токены 00, 01 и тд

In [12]:
# Обучение модели Logistic Regression из коробки
model = LogisticRegression(random_state=42, max_iter=1000)
model.fit(X_train_vectorized_bow, train_df['topic'])

# Предсказание на тестовой выборке
y_test_pred = model.predict(X_test_vectorized_bow)
print("Test Set Results :")
print("Accuracy:", accuracy_score(test_df['topic'], y_test_pred))
print("Classification Report:\n", classification_report(test_df['topic'], y_test_pred, zero_division=0))

# Предсказание на валидационной выборке
y_val_pred = model.predict(X_val_vectorized_bow)
print("Validation Set Results:")
print("Accuracy:", accuracy_score(val_df['topic'], y_val_pred))
print("Classification Report:\n", classification_report(val_df['topic'], y_val_pred, zero_division=0))

Test Set Results :
Accuracy: 0.77605
Classification Report:
                    precision    recall  f1-score   support

   69-я параллель       0.88      0.43      0.58        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.50      0.40      0.44       200
      Бывший СССР       0.80      0.75      0.77      1445
              Дом       0.83      0.78      0.80       588
         Из жизни       0.55      0.55      0.55       747
   Интернет и СМИ       0.72      0.68      0.70      1209
             Крым       0.67      0.22      0.33        18
    Культпросвет        1.00      0.22      0.36         9
         Культура       0.85      0.85      0.85      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.75      0.77      0.76      3698
  Наука и техника       0.80      0.80      0.80      1438
      Путешествия       0.71      0.64      0.67       174
           Россия       0.75      0.78      0.76      4343
Силовые структуры       0.56      0.50      0.53       530
            Спорт       0.96      0.95      0.96      1743
         Ценности       0.86      0.83      0.84       210
        Экономика       0.82      0.84      0.83      2152

         accuracy                           0.78     20000
        macro avg       0.68      0.58      0.61     20000
     weighted avg       0.78      0.78      0.77     20000

Validation Set Results:
Accuracy: 0.7724
Classification Report:
                    precision    recall  f1-score   support

   69-я параллель       0.67      0.29      0.41        34
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.45      0.34      0.39       200
      Бывший СССР       0.80      0.75      0.77      1445
              Дом       0.83      0.76      0.79       588
         Из жизни       0.56      0.57      0.56       747
   Интернет и СМИ       0.71      0.68      0.70      1209
             Крым       0.86      0.33      0.48        18
    Культпросвет        0.17      0.11      0.13         9
         Культура       0.84      0.83      0.83      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.76      0.78      0.77      3699
  Наука и техника       0.80      0.78      0.79      1438
      Путешествия       0.72      0.59      0.65       173
           Россия       0.74      0.79      0.76      4343
Силовые структуры       0.51      0.48      0.50       530
            Спорт       0.96      0.95      0.96      1743
         Ценности       0.85      0.83      0.84       210
        Экономика       0.80      0.83      0.81      2153

         accuracy                           0.77     20000
        macro avg       0.63      0.56      0.59     20000
     weighted avg       0.77      0.77      0.77     20000

Из коробки получились досаточно неплохие результаты, макро recall- 0.58 и precision 0.68. F1-macro - 0.61 Не смогли предсказать "Библиотека" и "Легпром", но на самом этих новостей очень мало, так что это норм. "Культпросвет" где всего 9 новостей уже есть какой-то recall и presicion

In [36]:
# Попробуем использовать TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_df=0.7, min_df=0.001)

X_train_vectorized_tfidf = tfidf_vectorizer.fit_transform(train_df['combined'])  # Обучение векторизатора и преобразование train
X_test_vectorized_tfidf = tfidf_vectorizer.transform(test_df['combined'])       # Преобразование test
X_val_vectorized_tfidf = tfidf_vectorizer.transform(val_df['combined'])

In [37]:
print('Количество уникальных токенов в нашем корпусе:',len(tfidf_vectorizer.get_feature_names_out()))

Количество уникальных токенов в нашем корпусе: 9149

In [15]:
# матрица с векторами tfidf
matrix_tfidf = pd.DataFrame(X_train_vectorized_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

assert matrix_tfidf.shape[0] == train_df.shape[0] and len(matrix_tfidf.columns) == len(tfidf_vectorizer.get_feature_names_out())

matrix_tfidf.head(3)

,00,01,02,03,04,05,06,07,08,09,...,ярославль,ярославский,ясир,ясный,яхта,яценюк,ячейка,яшин,ящик,ёмкость
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
del matrix_tfidf

In [17]:
# Обучение модели Logistic Regression из коробки
model = LogisticRegression(random_state=42, max_iter=1000)
model.fit(X_train_vectorized_tfidf, train_df['topic'])

# Предсказание на тестовой выборке
y_test_pred = model.predict(X_test_vectorized_tfidf)
print("Test Set Results :")
print("Accuracy:", accuracy_score(test_df['topic'], y_test_pred))
print("Classification Report:\n", classification_report(test_df['topic'], y_test_pred, zero_division=0))

# Предсказание на валидационной выборке
y_val_pred = model.predict(X_val_vectorized_tfidf)
print("Validation Set Results:")
print("Accuracy:", accuracy_score(val_df['topic'], y_val_pred))
print("Classification Report:\n", classification_report(val_df['topic'], y_val_pred, zero_division=0))

Test Set Results :
Accuracy: 0.8081
Classification Report:
                    precision    recall  f1-score   support

   69-я параллель       0.00      0.00      0.00        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.70      0.15      0.25       200
      Бывший СССР       0.82      0.79      0.80      1445
              Дом       0.85      0.78      0.81       588
         Из жизни       0.67      0.55      0.61       747
   Интернет и СМИ       0.76      0.71      0.74      1209
             Крым       0.50      0.11      0.18        18
    Культпросвет        0.00      0.00      0.00         9
         Культура       0.86      0.88      0.87      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.78      0.84      0.81      3698
  Наука и техника       0.82      0.84      0.83      1438
      Путешествия       0.85      0.58      0.69       174
           Россия       0.77      0.85      0.81      4343
Силовые структуры       0.72      0.37      0.48       530
            Спорт       0.96      0.96      0.96      1743
         Ценности       0.92      0.74      0.82       210
        Экономика       0.83      0.87      0.85      2152

         accuracy                           0.81     20000
        macro avg       0.62      0.53      0.55     20000
     weighted avg       0.80      0.81      0.80     20000

Validation Set Results:
Accuracy: 0.8074
Classification Report:
                    precision    recall  f1-score   support

   69-я параллель       1.00      0.06      0.11        34
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.62      0.13      0.21       200
      Бывший СССР       0.82      0.81      0.82      1445
              Дом       0.88      0.75      0.81       588
         Из жизни       0.68      0.56      0.62       747
   Интернет и СМИ       0.78      0.72      0.75      1209
             Крым       1.00      0.11      0.20        18
    Культпросвет        0.00      0.00      0.00         9
         Культура       0.86      0.87      0.86      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.79      0.84      0.82      3699
  Наука и техника       0.83      0.83      0.83      1438
      Путешествия       0.77      0.42      0.54       173
           Россия       0.76      0.84      0.80      4343
Силовые структуры       0.64      0.31      0.42       530
            Спорт       0.97      0.96      0.96      1743
         Ценности       0.91      0.76      0.83       210
        Экономика       0.81      0.88      0.84      2153

         accuracy                           0.81     20000
        macro avg       0.69      0.52      0.55     20000
     weighted avg       0.80      0.81      0.80     20000

Общие результаты по recall и presicion стали похуже, но теперь мы вообще не предсказываем класс Культпросвет. В целом в дальнейшем думаю, что можно попробовать подбирать параметры для векторов bagofwords, чтобы улучшить результаты

## Оптимизация и подбор параметров

In [16]:
# Создадим пайплайн для подобора параметров
pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),  # Векторизация текста
    ('clf', LogisticRegression(random_state=42))  # Модель классификации
])

In [28]:
# Сетка параметров для GridSearchCV, закомментил то, что хотелось бы еще попробовать перебрать, но не хватило времени и мощностей
param_grid = {
    # 'vectorizer__ngram_range': [(1, 1), (1, 2)],  # Униграммы или униграммы + биграммы
    # 'vectorizer__max_features': [5000, 10000, None],  # Ограничение на количество признаков
    'vectorizer__min_df': [0.001, 0.003, 0.01],  # Минимальная частота слова
    'vectorizer__max_df': [0.6, 0.75, 0.95],  # Максимальная частота слова
    'clf__C': [0.1, 1, 10],  # Параметр регуляризации
    # 'clf__penalty': ['l2'],  # Тип регуляризации
    # 'clf__solver': ['lbfgs', 'liblinear'],  # Алгоритм оптимизации
    # 'clf__max_iter': [500, 1000, 5000]  # Максимальное количество итераций
}

In [19]:
# Создаем кастомную обертку для RandomizedSearchCV с tqdm, чтобы отслеживать прогресс перебора
class RandomizedSearchCVWithProgress(RandomizedSearchCV):
    def _run_search(self, evaluate_candidates):
        # Используем tqdm для отслеживания прогресса
        with tqdm(total=self.n_iter, desc="RandomizedSearchCV") as pbar:
            def evaluate_candidates_with_progress(candidate_params):
                result = evaluate_candidates(candidate_params)
                pbar.update(len(candidate_params))  # Обновляем прогресс
                return result
            super()._run_search(evaluate_candidates_with_progress)

In [29]:
# загрузим параметры, будем оптимизировать f1 macro, так как у нас несбалансированные классы
randomized_search = RandomizedSearchCVWithProgress(pipeline, param_grid, n_iter=5, cv=2, scoring='f1_macro', n_jobs=-1, verbose=1, random_state=42)
randomized_search.fit(train_df['combined'], train_df['topic'])

RandomizedSearchCV:   0%|          | 0/5 [00:00<?, ?it/s]

Fitting 2 folds for each of 5 candidates, totalling 10 fits

RandomizedSearchCV: 100%|██████████| 5/5 [01:48<00:00, 21.79s/it]
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

RandomizedSearchCVWithProgress(cv=2,
                               estimator=Pipeline(steps=[('vectorizer',
                                                          CountVectorizer()),
                                                         ('clf',
                                                          LogisticRegression(random_state=42))]),
                               n_iter=5, n_jobs=-1,
                               param_distributions={'clf__C': [0.1, 1, 10],
                                                    'vectorizer__max_df': [0.6,
                                                                           0.75,
                                                                           0.95],
                                                    'vectorizer__min_df': [0.001,
                                                                           0.003,
                                                                           0.01]},
                               random_state=42, scoring='f1_macro', verbose=1)

In [34]:
# Лучшие параметры
print("Лучшие параметры:", randomized_search.best_params_)

# Обучение финальной модели на всей обучающей выборке с лучшими параметрами
best_model = randomized_search.best_estimator_

# Оценка на валидационной выборке
y_val_pred = best_model.predict(val_df['combined'])
print("Validation Set Results:")
print("Accuracy:", accuracy_score(val_df['topic'], y_val_pred))
print("F1-score (macro):", f1_score(val_df['topic'], y_val_pred, average='macro'))
print("Classification Report:\n", classification_report(val_df['topic'], y_val_pred, zero_division=0))

# Оценка на тестовой выборке
y_test_pred = best_model.predict(test_df['combined'])
print("Test Set Results:")
print("Accuracy:", accuracy_score(test_df['topic'], y_test_pred))
print("F1-score (macro):", f1_score(test_df['topic'], y_test_pred, average='macro'))
print("Classification Report:\n", classification_report(test_df['topic'], y_test_pred, zero_division=0))

Лучшие параметры: {'vectorizer__min_df': 0.001, 'vectorizer__max_df': 0.75, 'clf__C': 10}
Validation Set Results:
Accuracy: 0.76635
F1-score (macro): 0.5784354020502729
Classification Report:
                    precision    recall  f1-score   support

   69-я параллель       0.74      0.50      0.60        34
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.40      0.33      0.36       200
      Бывший СССР       0.80      0.74      0.77      1445
              Дом       0.81      0.77      0.79       588
         Из жизни       0.55      0.56      0.55       747
   Интернет и СМИ       0.71      0.69      0.70      1209
             Крым       0.62      0.28      0.38        18
    Культпросвет        0.00      0.00      0.00         9
         Культура       0.84      0.82      0.83      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.76      0.77      0.76      3699
  Наука и техника       0.80      0.76      0.78      1438
      Путешествия       0.66      0.60      0.63       173
           Россия       0.73      0.78      0.76      4343
Силовые структуры       0.50      0.49      0.49       530
            Спорт       0.96      0.95      0.96      1743
         Ценности       0.85      0.80      0.82       210
        Экономика       0.80      0.82      0.81      2153

         accuracy                           0.77     20000
        macro avg       0.61      0.56      0.58     20000
     weighted avg       0.77      0.77      0.77     20000

Test Set Results:
Accuracy: 0.769
F1-score (macro): 0.6053908630673206
Classification Report:
                    precision    recall  f1-score   support

   69-я параллель       0.88      0.43      0.58        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.50      0.40      0.45       200
      Бывший СССР       0.77      0.75      0.76      1445
              Дом       0.82      0.78      0.80       588
         Из жизни       0.53      0.55      0.54       747
   Интернет и СМИ       0.71      0.68      0.69      1209
             Крым       0.64      0.39      0.48        18
    Культпросвет        1.00      0.11      0.20         9
         Культура       0.85      0.85      0.85      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.74      0.76      0.75      3698
  Наука и техника       0.80      0.79      0.80      1438
      Путешествия       0.74      0.67      0.70       174
           Россия       0.74      0.77      0.75      4343
Силовые структуры       0.54      0.52      0.53       530
            Спорт       0.96      0.95      0.95      1743
         Ценности       0.86      0.83      0.84       210
        Экономика       0.82      0.82      0.82      2152

         accuracy                           0.77     20000
        macro avg       0.68      0.58      0.61     20000
     weighted avg       0.77      0.77      0.77     20000

**Вывод:** Так как нет больших вычислительный мощностей, то особо не удалось найти лучше параметры и улучшить результат модели. F1 мера, recall и precision остались примерно на том же уровне.

**Заключение**

Таким образом, я познакомился с основными способами предобработки текста (фильтрация стопслов, лемматизация и фильтры на числа и тд), также смог применить методы векторизации bag of words и tf-idf и построил классификатор новостей на основе логистической регресии

**Что можно еще попробовать, чтобы улучшить результат:**

1) Построить векторы для текста и заголовка отдельно и усреднить / сложить их, также можно попробовать задачть им разный вес \
2) Попробовать стемминг вместо леммотизации, чтобы облегчить предобработку текста \
3) Поиграться с большим количеством парамаетров и попробовать оптимизировать tf-idf вместо bag of words \
4) Подумать над тем, как улучшить предобработку текста